sudo: required
language: generic 
services:
    - docker
before_install:
    docker build -t tharoon/fibreact-ci -f ./client/Dockerfile.dev ./client
        
script:
    docker run -e CI=true tharoon/fibreact-ci npm test

after_success:
    - docker build -t tharoon/tcubefibreact-client ./client
    - docker build -t tharoon/tcubefibreact-nginx ./nginx
    - docker build -t tharoon/tcubefibreact-server ./server
    - docker build -t tharoon/tcubefibreact-worker ./worker
# Login into the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
# Take those images and push them into docker hub
    - docker push tharoon/tcubefibreact-client
    - docker push tharoon/tcubefibreact-nginx
    - docker push tharoon/tcubefibreact-server
    - docker push tharoon/tcubefibreact-worker